#!/bin/bash

SHORT=p:,h
LONG=process:,help
OPTS=$(getopt -a -n weather --options $SHORT --longoptions $LONG -- "$@")

eval set -- "$OPTS"

while :
do
  case "$1" in
    -p | --process )
      process="$2"
      #-----------------Common IOCs--------------------------#
      if [ "$process" == "shutterIOC" ] ; then
        ssh -X dev.control@10.3.5.21 "
            tmux send-keys -t  ShutterIOC.0 "exit" ENTER 
            "   

      elif [ "$process" == "motorIOC" ] ; then
        ssh -X root@10.1.50.12 "
            tmux send-keys -t MotorIOC.0 "exit" ENTER
            "

      elif [ "$process" == "tomoscanSupportIOC" ] ; then
        ssh -X root@10.1.50.16 "
            tmux send-keys -t TomoscanSupportIOC "exit" ENTER
            "

      elif [ "$process" == "writerSupportIOC" ] ; then
        ssh -X root@10.1.32.30 "
            tmux send-keys -t WriterSupportIOC "exit" ENTER 
            "
      #---------------------PCO & FLIR IOCs --------------------#
      elif [ "$process" == "FLIRIOC" ] ; then
        tmux send-keys -t FLIR_CameraIOC C-c
        sleep 0.5
        tmux send-keys -t FLIR_CameraIOC "exit" ENTER 
        tmux send-keys -t FLIR_CameraIOC "sleep 0.5" ENTER
        tmux send-keys -t FLIR_CameraIOC "exit" ENTER 

      #---------------------PCO Step Scan --------------------#
      elif [ "$process" == "PCO_StepTomoscanIOC" ] ; then
        tmux send-keys -t PCO_StepTomoscanIOC "exit" ENTER 

      elif [ "$process" == "PCO_PythonServerStep" ] ; then
        tmux send-keys -t PCO_PythonServerStep "exit()" ENTER
        sleep 1
        tmux send-keys -t PCO_PythonServerStep "exit" ENTER

      elif [ "$process" == "PCO_WriterServerStep" ] ; then
        tmux send-keys -t PCO_WriterServerStep C-c
        sleep 1 
        tmux send-keys -t PCO_WriterServerStep "exit()" ENTER
        sleep 1
        tmux send-keys -t PCO_WriterServerStep "exit" ENTER
        sleep 1.5
        tmux send-keys -t PCO_WriterServerStep "exit" ENTER

      #---------------------PCO Continuous Scan --------------------#
      elif [ "$process" == "PCO_ContTomoscanIOC" ] ; then
        tmux send-keys -t PCO_ContTomoscanIOC "exit" ENTER

      elif [ "$process" == "PCO_PythonServerCont" ] ; then
        tmux send-keys -t PCO_PythonServerCont "exit()" ENTER
        sleep 1 
        tmux send-keys -t PCO_PythonServerCont "exit" ENTER

      elif [ "$process" == "PCO_WriterServerCont" ] ; then
        tmux send-keys -t PCO_WriterServerCont C-c
        sleep 1 
        tmux send-keys -t PCO_WriterServerCont "exit()" ENTER
        sleep 1
        tmux send-keys -t PCO_WriterServerCont "exit" ENTER
        sleep 1.5
        tmux send-keys -t PCO_WriterServerCont "exit" ENTER

      #---------------------FLIR Step Scan --------------------#
      elif [ "$process" == "FLIR_StepTomoscanIOC" ] ; then
        tmux send-keys -t FLIR_StepTomoscanIOC "exit" ENTER 

      elif [ "$process" == "FLIR_PythonServerStep" ] ; then
        tmux send-keys -t FLIR_PythonServerStep "exit()" ENTER
        sleep 1 
        tmux send-keys -t FLIR_PythonServerStep "exit" ENTER 
            
      elif [ "$process" == "FLIR_WriterServerStep" ] ; then
        tmux send-keys -t FLIR_WriterServerStep C-c
        sleep 1 
        tmux send-keys -t FLIR_WriterServerStep "exit()" ENTER
        sleep 1
        tmux send-keys -t FLIR_WriterServerStep "exit" ENTER
        sleep 1.5
        tmux send-keys -t FLIR_WriterServerStep "exit" ENTER

      #---------------------FLIR Continuous Scan --------------------#
      elif [ "$process" == "FLIR_ContTomoscanIOC" ] ; then
        tmux send-keys -t FLIR_ContTomoscanIOC "exit" ENTER 
            
      elif [ "$process" == "FLIR_PythonServerCont" ] ; then
        tmux send-keys -t FLIR_PythonServerCont "exit()" ENTER
        sleep 1 
        tmux send-keys -t FLIR_PythonServerCont "exit" ENTER 
            
      elif [ "$process" == "FLIR_WriterServerCont" ] ; then
        tmux send-keys -t FLIR_WriterServerCont C-c
        sleep 1 
        tmux send-keys -t FLIR_WriterServerCont "exit()" ENTER
        sleep 1
        tmux send-keys -t FLIR_WriterServerCont "exit" ENTER
        sleep 1.5
        tmux send-keys -t FLIR_WriterServerCont "exit" ENTER

    #-----------------------------------------#
      else 
          echo "Unknow process option has been provided!!"
    fi
      shift 2
      ;;
    -h | --help)
      printf "\n"
      echo "============= Stop BEATS process options ============="
      echo " >>>>> Commom IOCs <<<<<"
      echo " --process shutterIOC "
      echo " --process MotorIOC"
      echo " --process tomoscanSupportIOC"
      echo " --process writerSupportIOC"
      echo " --------------------------"
      echo " >>>>> PCO & FLIR IOCs <<<<<"
      echo " --process FLIRIOC"
      echo " --------------------------"
      echo " >>>>> PCO Step or Continuous Scan <<<<<"
      echo -e " Step Scan: \t\t\t\t Continuous Scan:"                                       
      echo -e " --process PCO_StepTomoscanIOC \t\t --process PCO_ContTomoscanIOC"
      echo -e " --process PCO_PythonServerStep \t --process PCO_PythonServerCont"
      echo -e " --process PCO_WriterServerStep \t --process PCO_WriterServerCont"
      echo " --------------------------"
      echo " >>>>> FLIR Step or Continuous Scan <<<<<"
      echo -e " Step Scan: \t\t\t\t Continuous Scan:"                                       
      echo -e " --process FLIR_StepTomoscanIOC \t --process FLIR_ContTomoscanIOC"
      echo -e " --process FLIR_PythonServerStep \t --process FLIR_PythonServerCont"
      echo -e " --process FLIR_WriterServerStep \t --process FLIR_WriterServerCont"
      echo "===================================================="
      printf "\n"
      exit 2
      ;;
    --)
      shift;
      break
      ;;
    *)
      echo "Unexpected option: $1"
      ;;
  esac
done

echo $process
