#!/bin/bash

SHORT=p:,h
LONG=process:,help
OPTS=$(getopt -a -n weather --options $SHORT --longoptions $LONG -- "$@")

eval set -- "$OPTS"

while :
do
  case "$1" in
    -p | --process )
      process="$2"
      #-----------------Common IOCs--------------------------#
      if [ "$process" == "shutterIOC" ] ; then
        ssh -X dev.control@10.1.50.5 "
            cd /home/dev.control/top/mirrors
            tmux new -d -s ShutterIOC './bin/linux-x86_64/ioc iocBoot/ioc/st.cmd'"

      elif [ "$process" == "motorIOC" ] ; then
        ssh -X root@10.1.50.12 "
            cd /opt/top/motor-sim 
            tmux new -d -s MotorIOC './bin/linux-x86_64/ioc iocBoot/ioc/st.cmd ' "

      elif [ "$process" == "tomoscanSupportIOC" ] ; then
        ssh -X root@10.1.50.16 "
            cd /opt/epics7/synApps/support/suppIoc
            tmux new -d -s TomoscanSupportIOC 
            tmux send-keys -t TomoscanSupportIOC.0 \"softIoc -d suppIoc.db\"
            tmux send-keys -t TomoscanSupportIOC.0 ENTER
            "

      elif [ "$process" == "writerSupportIOC" ] ; then
        ssh -X root@10.1.50.207 "
            cd /opt/DAQ/IOCs/BEATS_DAQ_Supp_IOC 
            tmux  new -d -s WriterSupportIOC
            tmux send-keys -t WriterSupportIOC \"softIoc -d writerStatus.db\" ENTER 
            "
      #---------------------PCO & FLIR IOCs --------------------#
      elif [ "$process" == "FLIRIOC" ] ; then
        ssh -X root@10.1.50.207 "
            cd /root/ad-iaxd
            sleep 1 
            tmux new -d -s FLIR_CameraIOC './bin/linux-x86_64/ad-iaxd iocBoot/iocad-iaxd/st.cmd' 
            "

      elif [ "$process" == "FLIRDriver" ] ; then
        ssh -X root@10.1.50.207 "
            cd && /root/run-gui.sh
            "

      elif [ "$process" == "PCODriver" ] ; then
          ssh -X sesame@10.1.50.5 "
            medm -x -macro "P=TEST-PCO:,R=cam1:" /home/sesame/medm-files/ADBase.adl
          "
      #---------------------PCO Step Scan --------------------#
      elif [ "$process" == "PCO_StepTomoscanIOC" ] ; then
        cd /opt/epics/synApps/support/tomoscan/iocBoot/iocTomoScan_BEATS_Step 
        tmux new -d -s PCO_StepTomoscanIOC './start_IOC' 

      elif [ "$process" == "PCO_PythonServerStep" ] ; then
        cd /opt/epics/synApps/support/tomoscan/iocBoot/iocTomoScan_BEATS_Step
        tmux new -d -s PCO_PythonServerStep 
        tmux send-keys -t PCO_PythonServerStep "./start_python" ENTER

      elif [ "$process" == "PCO_WriterServerStep" ] ; then
        ssh -X root@10.1.50.207 "
            cd /opt/DAQ/BEATSH5Writer
            sleep 1
            source /opt/DAQ/venv/bin/activate
            sleep 1
            tmux new -d -s PCO_WriterServerStep
            sleep 1
            tmux send-keys -t PCO_WriterServerStep "xvfb-run" Space "./start_writer" Space "--scanMode" Space "PCO-step" ENTER
            "

      elif [ "$process" == "PCO_StepMEDM" ] ; then
        ssh -X root@localhost "
          medm  -x -macro "P=BEATS_STEP:,R=TomoScan:,BEAMLINE=TomoScan_BEATS" /opt/epics/synApps/support/tomoscan/tomoScanApp/op/adl/tomoScan.adl &
        "
      #---------------------PCO Continuous Scan --------------------#
      elif [ "$process" == "PCO_ContTomoscanIOC" ] ; then
        cd /opt/epics/synApps/support/tomoscan/iocBoot/iocTomoScan_BEATS_Continuous
        tmux new -d -s PCO_ContTomoscanIOC './start_IOC'

      elif [ "$process" == "PCO_PythonServerCont" ] ; then
        cd /opt/epics/synApps/support/tomoscan/iocBoot/iocTomoScan_BEATS_Continuous 
        tmux new -d -s PCO_PythonServerCont
        tmux send-keys -t PCO_PythonServerCont "./start_python" ENTER

      elif [ "$process" == "PCO_WriterServerCont" ] ; then
        ssh -X root@10.1.50.207 "
            cd /opt/DAQ/BEATSH5Writer
            source /opt/DAQ/venv/bin/activate
            sleep 1
            tmux new -d -s PCO_WriterServerCont
            sleep 1
            tmux send-keys -t PCO_WriterServerCont "xvfb-run" Space "./start_writer" Space "--scanMode" Space "PCO-cont" ENTER
            "

      elif [ "$process" == "PCO_ContMEDM" ] ; then
        ssh -X root@localhost "
          medm  -x -macro "P=BEATS_CONTINUOUS:,R=TomoScan:,BEAMLINE=TomoScan_BEATS" /opt/epics/synApps/support/tomoscan/tomoScanApp/op/adl/tomoScan.adl &
        "
      #---------------------FLIR Step Scan --------------------#
      elif [ "$process" == "FLIR_StepTomoscanIOC" ] ; then
        ssh -X root@10.1.50.4 "
            cd /opt/epics/support/tomoscan/iocBoot/iocTomoScan_BEATS_Step
            sleep 1
            tmux new -d -s FLIR_StepTomoscanIOC './start_IOC' 
            " 

      elif [ "$process" == "FLIR_PythonServerStep" ] ; then
        ssh -X root@10.1.50.4 "
            cd /opt/epics/support/tomoscan/iocBoot/iocTomoScan_BEATS_Step
            sleep 1
            source /opt/SW/venv3.9/bin/activate
            sleep 1
            tmux new -d -s FLIR_PythonServerStep
            sleep 1
            tmux send-keys -t FLIR_PythonServerStep "xvfb-run" Space "python" Space "-i" Space "start_tomoscan.py" ENTER
            "

      elif [ "$process" == "FLIR_WriterServerStep" ] ; then
        ssh -X root@10.1.50.207 "
            cd /opt/DAQ/BEATSH5Writer
            sleep 1
            source /opt/DAQ/venv/bin/activate
            sleep 1
            tmux new -d -s FLIR_WriterServerStep
            sleep 1
            tmux send-keys -t FLIR_WriterServerStep "xvfb-run" Space "./start_writer" Space "--scanMode" Space "FLIR-step" ENTER
            "

      elif [ "$process" == "FLIR_StepMEDM" ] ; then
          ssh -X root@10.1.50.4 "medm -x -macro "P=beats:,R=TomoScanStep:,BEAMLINE=tomoScanStep_beats" /opt/epics/support/tomoscan/tomoScanApp/op/adl/tomoScan.adl &"
      #---------------------FLIR Continuous Scan --------------------#
      elif [ "$process" == "FLIR_ContTomoscanIOC" ] ; then
        ssh -X root@10.1.50.4 "
            cd /opt/epics/support/tomoscan/iocBoot/iocTomoScan_BEATS_Cont
            sleep 1 
            source /opt/SW/venv3.9/bin/activate
            sleep 1
            tmux new -d -s FLIR_ContTomoscanIOC './start_IOC' 
            "

      elif [ "$process" == "FLIR_PythonServerCont" ] ; then
        ssh -X root@10.1.50.4 "
            cd /opt/epics/support/tomoscan/iocBoot/iocTomoScan_BEATS_Cont
            sleep 1
            source /opt/SW/venv3.9/bin/activate
            sleep 1
            tmux new -d -s FLIR_PythonServerCont
            sleep 1
            tmux send-keys -t FLIR_PythonServerCont "xvfb-run" Space "python" Space "-i" Space "start_tomoscan.py" ENTER
            "

      elif [ "$process" == "FLIR_WriterServerCont" ] ; then
        ssh -X root@10.1.50.207 "
            cd /opt/DAQ/BEATSH5Writer
            sleep 1
            source /opt/DAQ/venv/bin/activate
            sleep 1
            tmux new -d -s FLIR_WriterServerCont
            sleep 1
            tmux send-keys -t FLIR_WriterServerCont "xvfb-run" Space "./start_writer" Space "--scanMode" Space "FLIR-cont" ENTER
            "
            
      elif [ "$process" == "FLIR_ContMEDM" ] ; then
          ssh -X root@10.1.50.4 "medm -x -macro "P=beats:,R=TomoScanCont:,BEAMLINE=tomoScan_beats" /opt/epics/support/tomoscan/tomoScanApp/op/adl/tomoScan.adl &"
    #-----------------------------------------#
      elif [ "$process" == "ImageJ" ] ; then
        cd /opt/SW/ImageJ
        ./ImageJ
      else 
          echo "Unknow process option has been provided!!"
    fi
      shift 2
      ;;
    -h | --help)
      printf "\n"
      echo "============= Start BEATS process options ============="
      echo " >>>>> Commom IOCs <<<<<"
      echo " --process shutterIOC "
      echo " --process MotorIOC"
      echo " --process tomoscanSupportIOC"
      echo " --process writerSupportIOC"
      echo " --------------------------"
      echo " >>>>> PCO & FLIR IOCs <<<<<"
      echo " --process FLIRIOC"
      echo " --process FLIRDriver"
      echo " --process PCODriver"
      echo " --------------------------"
      echo " >>>>> PCO Step or Continuous Scan <<<<<"
      echo -e " Step Scan: \t\t\t\t Continuous Scan:"                                       
      echo -e " --process PCO_StepTomoscanIOC \t\t --process PCO_ContTomoscanIOC"
      echo -e " --process PCO_PythonServerStep \t --process PCO_PythonServerCont"
      echo -e " --process PCO_WriterServerStep \t --process PCO_WriterServerCont"
      echo -e " --process PCO_StepMEDM \t\t --process PCO_ContMEDM"
      echo " --------------------------"
      echo " >>>>> FLIR Step or Continuous Scan <<<<<"
      echo -e " Step Scan: \t\t\t\t Continuous Scan:"                                       
      echo -e " --process FLIR_StepTomoscanIOC \t --process FLIR_ContTomoscanIOC"
      echo -e " --process FLIR_PythonServerStep \t --process FLIR_PythonServerCont"
      echo -e " --process FLIR_WriterServerStep \t --process FLIR_WriterServerCont"
      echo -e " --process FLIR_StepMEDM \t\t --process FLIR_ContMEDM"
      echo " --------------------------"
      echo " >>>>> ImageJ <<<<<"
      echo " --process ImageJ"
      echo "===================================================="
      printf "\n"
      exit 2
      ;;
    --)
      shift;
      break
      ;;
    *)
      echo "Unexpected option: $1"
      ;;
  esac
done

echo $process
