#!/bin/bash

SHORT=p:,h
LONG=process:,help
OPTS=$(getopt -a -n weather --options $SHORT --longoptions $LONG -- "$@")

eval set -- "$OPTS"

while :
do
  case "$1" in
    -p | --process )
      process="$2"
      #-----------------Common IOCs--------------------------#
      if [ "$process" == "motorIOC" ] ; then
        # ssh -X dev.control@motionstage "
        #     cd /home/dev.control/micos-ioc 
        #     tmux send-keys -t MicosIOC.0 "exit" ENTER
        #     sleep 2
        #     tmux new -d -s MicosIOC './bin/linux-x86_64/ioc iocBoot/ioc/st.cmd'
        #     "
        tmux send-keys -t MicosStageIOC C-c
        sleep 0.5
        tmux send-keys -t MicosStageIOC "sleep 0.5" ENTER
        tmux send-keys -t MicosStageIOC "cd /home/dev.control/micos-ioc; ./bin/linux-x86_64/ioc iocBoot/ioc/st.cmd" ENTER


      elif [ "$process" == "tomoscanSupportIOC" ] ; then
        tmux send-keys -t TomoscanSupportIOC C-c
        sleep 0.5
        tmux send-keys -t TomoscanSupportIOC "cd /home/control/DAQ/operation/TomoscanSupportIOCs/tomoscanSupport; ./bin/linux-x86_64/tomoscanSupp iocBoot/ioctomoscanSupp/st.cmd" ENTER

      elif [ "$process" == "writerSupportIOC" ] ; then
        ssh -X control@writernode "
            cd /home/control/BEATS_DAQ_Supp_IOC/supportIOC
            tmux send-keys -t WriterSupportIOC "exit" ENTER
            sleep 2
            tmux  new -d -s WriterSupportIOC 
            tmux send-keys -t WriterSupportIOC \"./bin/linux-x86_64/Supp iocBoot/iocSupp/st.cmd\" ENTER
            "

      elif [ "$process" == "SSCAN_IOC" ] ; then
        tmux send-keys -t SSCAN_IOC C-c
        sleep 0.5
        tmux send-keys -t SSCAN_IOC "cd /home/control/DAQ/operation/TomoscanSupportIOCs/sscanIOC/iocBoot/ioctool; ../../bin/linux-x86_64/tool st.cmd" ENTER
        
      #---------------------PCO & FLIR IOCs --------------------#
      elif [ "$process" == "FLIRIOC" ] ; then
        tmux send-keys -t FLIR_CameraIOC "exit" ENTER
        sleep 1
        # tmux send-keys -t FLIR_CameraIOC.0 "sleep 0.5" ENTER
        tmux send-keys -t FLIR_CameraIOC.0 "./bin/linux-x86_64/ad-iaxd iocBoot/iocad-iaxd/st.cmd " ENTER

      #---------------------PCO Step Scan --------------------#
      elif [ "$process" == "PCO_StepTomoscanIOC" ] ; then
        tmux send-keys -t PCO_StepTomoscanIOC "exit" ENTER 
        sleep 2
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_PCO_MICOS_Step
        tmux new -d -s PCO_StepTomoscanIOC './start_IOC'
        # tmux kill-session -t RPTriggerServer
        # tmux new -d -s RPTriggerServer
        # tmux send-keys -t RPTriggerServer "ssh sesame@rasppi" ENTER
        # tmux send-keys -t RPTriggerServer "RPTrigServ"

      elif [ "$process" == "PCO_PythonServerStep" ] ; then
        tmux kill-session -t PCO_PythonServerStep
        # tmux send-keys -t PCO_PythonServerStep "exit()" ENTER
        sleep 0.5
        # source /opt/SW/venv3.9/bin/activate
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_PCO_MICOS_Step
        tmux new -d -s PCO_PythonServerStep 
        tmux send-keys -t PCO_PythonServerStep "p3; python -i start_tomoscan.py" ENTER
        # tmux send-keys -t PCO_PythonServerStep "python -i start_tomoscan.py" ENTER  

      elif [ "$process" == "PCO_WriterServerStep" ] ; then
        tmux kill-session -t PCO_WriterServerStep
        # tmux send-keys -t PCO_WriterServerStep C-c
        # sleep 1 
        # tmux send-keys -t PCO_WriterServerStep "exit()" ENTER
        sleep 0.5
        tmux new -d -s PCO_WriterServerStep
        tmux send-keys -t PCO_WriterServerStep "ssh -X control@writernode" ENTER
        tmux send-keys -t PCO_WriterServerStep "cd /home/control/BEATSH5Writer; p3; ./start_writer --scanMode PCO-MICOS-Step" ENTER
        # tmux send-keys -t PCO_WriterServerStep "./start_writer --scanMode PCO-MICOS-Step" ENTER
            
      #---------------------PCO Continuous Scan --------------------#
      elif [ "$process" == "PCO_ContTomoscanIOC" ] ; then
        tmux send-keys -t PCO_ContTomoscanIOC "exit" ENTER 
        sleep 2 
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_PCO_MICOS_Cont 
        tmux new -d -s PCO_ContTomoscanIOC './start_IOC'

      elif [ "$process" == "PCO_PythonServerCont" ] ; then
        tmux kill-session -t PCO_PythonServerCont
        # tmux send-keys -t PCO_PythonServerCont "exit()" ENTER
        sleep 0.5
        # source /opt/SW/venv3.9/bin/activate
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_PCO_MICOS_Cont
        tmux new -d -s PCO_PythonServerCont
        tmux send-keys -t PCO_PythonServerCont "p3; python -i start_tomoscan.py" ENTER
        # tmux send-keys -t PCO_PythonServerCont "python -i start_tomoscan.py" ENTER  

      elif [ "$process" == "PCO_WriterServerCont" ] ; then
        tmux kill-session -t PCO_WriterServerCont
        # tmux send-keys -t PCO_WriterServerCont C-c
        sleep 0.5 
        # tmux send-keys -t PCO_WriterServerCont "exit()" ENTER
        # sleep 1
        tmux new -d -s PCO_WriterServerCont
        tmux send-keys -t PCO_WriterServerCont "ssh -X control@writernode" ENTER
        tmux send-keys -t PCO_WriterServerCont "cd /home/control/BEATSH5Writer; p3; ./start_writer --scanMode PCO-MICOS-Cont" ENTER
        # tmux send-keys -t PCO_WriterServerCont "./start_writer --scanMode FLIR-MICOS-Cont" ENTER

      #---------------------FLIR Step Scan --------------------#
      elif [ "$process" == "FLIR_StepTomoscanIOC" ] ; then
        tmux send-keys -t FLIR_StepTomoscanIOC "exit" ENTER 
        sleep 2
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_FLIR_MICOS_Step
        tmux new -d -s FLIR_StepTomoscanIOC './start_IOC' 

      elif [ "$process" == "FLIR_PythonServerStep" ] ; then
        tmux kill-session -t FLIR_PythonServerStep
        # tmux send-keys -t FLIR_PythonServerStep "exit()" ENTER
        sleep 0.5
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_FLIR_MICOS_Step
        # source /opt/SW/venv3.9/bin/activate
        tmux new -d -s FLIR_PythonServerStep
        tmux send-keys -t FLIR_PythonServerStep "p3; python -i start_tomoscan.py" ENTER
        # tmux send-keys -t FLIR_PythonServerStep "python -i start_tomoscan.py" ENTER    

      elif [ "$process" == "FLIR_WriterServerStep" ] ; then
        tmux kill-session -t FLIR_WriterServerStep
        # tmux send-keys -t FLIR_WriterServerStep C-c
        sleep 0.5
        # tmux send-keys -t FLIR_WriterServerStep "exit()" ENTER
        # sleep 1
        tmux new -d -s FLIR_WriterServerStep 
        tmux send-keys -t FLIR_WriterServerStep "ssh -X control@writernode" ENTER
        tmux send-keys -t FLIR_WriterServerStep "cd /home/control/BEATSH5Writer; p3; ./start_writer --scanMode FLIR-MICOS-Step" ENTER
        # tmux send-keys -t FLIR_WriterServerStep "./start_writer --scanMode FLIR-MICOS-Step" ENTER

      #---------------------FLIR Continuous Scan --------------------#
      elif [ "$process" == "FLIR_ContTomoscanIOC" ] ; then
        tmux send-keys -t FLIR_ContTomoscanIOC "exit" ENTER 
        sleep 2
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_FLIR_MICOS_Cont 
        tmux new -d -s FLIR_ContTomoscanIOC './start_IOC' 
          
      elif [ "$process" == "FLIR_PythonServerCont" ] ; then
        tmux kill-session -t FLIR_PythonServerCont
        # tmux send-keys -t FLIR_PythonServerCont "exit()" ENTER
        sleep 0.5 
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_FLIR_MICOS_Cont 
        tmux new -d -s FLIR_PythonServerCont
        tmux send-keys -t FLIR_PythonServerCont "p3; python -i start_tomoscan.py" ENTER
        # tmux send-keys -t FLIR_PythonServerCont "python -i start_tomoscan.py" ENTER
        
      elif [ "$process" == "FLIR_WriterServerCont" ] ; then
        tmux kill-session -t FLIR_WriterServerCont
        tmux send-keys -t FLIR_WriterServerCont C-c
        sleep 0.5
        # tmux send-keys -t FLIR_WriterServerCont "exit()" ENTER
        # sleep 1
        tmux new -d -s FLIR_WriterServerCont
        tmux send-keys -t FLIR_WriterServerCont "ssh -X control@writernode" ENTER
        tmux send-keys -t FLIR_WriterServerCont "cd /home/control/BEATSH5Writer; p3; ./start_writer --scanMode FLIR-MICOS-Cont" ENTER
        # tmux send-keys -t FLIR_WriterServerCont "./start_writer --scanMode FLIR-MICOS-Cont" ENTER

    #-----------------------------------------#
      else 
          echo "Unknow process option has been provided!!"
    fi
      shift 2
      ;;
    -h | --help)
      printf "\n"
      echo "============= Restart BEATS process options ============="
      echo " >>>>> Commom IOCs <<<<<"
      echo " --process shutterIOC "
      echo " --process MotorIOC"
      echo " --process tomoscanSupportIOC"
      echo " --process writerSupportIOC"
      echo " --------------------------"
      echo " >>>>> PCO & FLIR IOCs <<<<<"
      echo " --process FLIRIOC"
      echo " --------------------------"
      echo " >>>>> PCO Step or Continuous Scan <<<<<"
      echo -e " Step Scan: \t\t\t\t Continuous Scan:"                                       
      echo -e " --process PCO_StepTomoscanIOC \t\t --process PCO_ContTomoscanIOC"
      echo -e " --process PCO_PythonServerStep \t --process PCO_PythonServerCont"
      echo -e " --process PCO_WriterServerStep \t --process PCO_WriterServerCont"
      echo " --------------------------"
      echo " >>>>> FLIR Step or Continuous Scan <<<<<"
      echo -e " Step Scan: \t\t\t\t Continuous Scan:"                                       
      echo -e " --process FLIR_StepTomoscanIOC \t --process FLIR_ContTomoscanIOC"
      echo -e " --process FLIR_PythonServerStep \t --process FLIR_PythonServerCont"
      echo -e " --process FLIR_WriterServerStep \t --process FLIR_WriterServerCont"
      echo "===================================================="
      printf "\n"
      exit 2
      ;;
    --)
      shift;
      break
      ;;
    *)
      echo "Unexpected option: $1"
      ;;
  esac
done

echo $process
