#!/bin/bash

SHORT=p:,h
LONG=process:,help
OPTS=$(getopt -a -n weather --options $SHORT --longoptions $LONG -- "$@")

eval set -- "$OPTS"

while :
do
  case "$1" in
    -p | --process )
      process="$2"
      #-----------------Common IOCs--------------------------#
      if [ "$process" == "motorIOC" ] ; then
        # ssh -X dev.control@motionstage "
            # cd /home/dev.control/micos-ioc 
            # tmux new -d -s MicosIOC './bin/linux-x86_64/ioc iocBoot/ioc/st.cmd ' "
        tmux new -d -s MicosStageIOC
        tmux send-keys -t MicosStageIOC "ssh -X dev.control@motionstage" ENTER
        tmux send-keys -t MicosStageIOC "cd /home/dev.control/micos-ioc; ./bin/linux-x86_64/ioc iocBoot/ioc/st.cmd" ENTER

      elif [ "$process" == "motorGUI" ] ; then
        ssh -X dev.control@motionstage "
            cd /home/dev.control/micos-ioc/ ;
            ./motor-gui.sh
            "

      elif [ "$process" == "tomoscanSupportIOC" ] ; then
        ssh -X root@tomoscansupport "
            cd /opt/epics7/synApps/support/suppIoc
            tmux new -d -s TomoscanSupportIOC 
            tmux send-keys -t TomoscanSupportIOC.0 \"softIoc -d suppIoc.db\"
            tmux send-keys -t TomoscanSupportIOC.0 ENTER
            "

      elif [ "$process" == "writerSupportIOC" ] ; then
        ssh -X root@writernode "
            cd /opt/DAQ/BEATS_DAQ_Supp_IOC/supportIOC
            tmux new -d -s WriterSupportIOC 
            tmux send-keys -t WriterSupportIOC \"./bin/linux-x86_64/Supp iocBoot/iocSupp/st.cmd\"
            tmux send-keys -t WriterSupportIOC ENTER
            "
      #---------------------PCO & FLIR IOCs --------------------#
      elif [ "$process" == "FLIRIOC" ] ; then
        tmux new -d -s FLIR_CameraIOC
        tmux send-keys -t FLIR_CameraIOC "ssh -X root@flirdriver" ENTER
        tmux send-keys -t FLIR_CameraIOC "cd /home/dev.control/ioc; ./bin/linux-x86_64/ad-iaxd iocBoot/iocad-iaxd/st.cmd" ENTER

      elif [ "$process" == "FLIRDriver" ] ; then
        ssh -X root@flirdriver "
            cd && /home/dev.control/run-GUI-ORYX.sh
            "

      elif [ "$process" == "PCODriver" ] ; then
          ssh -X sesame@pcodriver "
            nohup medm -x -macro "P=TEST-PCO:,R=cam1:" /home/sesame/medm-files/ADBase.adl &
          "
      #---------------------PCO Step Scan --------------------#
      elif [ "$process" == "PCO_StepTomoscanIOC" ] ; then
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_PCO_MICOS_Step 
        tmux new -d -s PCO_StepTomoscanIOC './start_IOC' 
        tmux new -d -s RPTriggerServer
        tmux send-keys -t RPTriggerServer "ssh sesame@rasppi" ENTER
        tmux send-keys -t RPTriggerServer "cd /home/sesame/RP; python3.9 server.py" ENTER

      elif [ "$process" == "PCO_PythonServerStep" ] ; then
        tmux kill-session -t PCO_PythonServerStep
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_PCO_MICOS_Step
        #source /opt/SW/venv3.9/bin/activate
        tmux new -d -s PCO_PythonServerStep 
        tmux send-keys -t PCO_PythonServerStep "p3; python -i start_tomoscan.py" ENTER 

      elif [ "$process" == "PCO_WriterServerStep" ] ; then
        tmux kill-session -t PCO_WriterServerStep
        tmux new -d -s PCO_WriterServerStep
        tmux send-keys -t PCO_WriterServerStep "ssh -X control@writernode" ENTER
        tmux send-keys -t PCO_WriterServerStep "cd /home/control/BEATSH5Writer; source /opt/operation/p3.9/bin/activate; ./start_writer --scanMode PCO-MICOS-Step" ENTER

      elif [ "$process" == "PCO_StepMEDM" ] ; then
        ssh -X control@localhost "
          nohup medm -x -macro "P=tomoscanBEATS:,R=PcoMicosStep:,BEAMLINE=tomoScan_BEATS_PCO_MICOS_Step" /opt/epics/support/BEATS_tomoscan/tomoScanApp/op/adl/tomoScan-Step.adl &
        "
      #---------------------PCO Continuous Scan --------------------#
      elif [ "$process" == "PCO_ContTomoscanIOC" ] ; then
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_PCO_MICOS_Cont
        tmux new -d -s PCO_ContTomoscanIOC './start_IOC'

      elif [ "$process" == "PCO_PythonServerCont" ] ; then
        tmux kill-session -t PCO_PythonServerCont
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_PCO_MICOS_Cont
        #source /opt/SW/venv3.9/bin/activate
        tmux new -d -s PCO_PythonServerCont
        tmux send-keys -t PCO_PythonServerCont "p3; python -i start_tomoscan.py" ENTER ;

      elif [ "$process" == "PCO_WriterServerCont" ] ; then
        tmux kill-session -t PCO_WriterServerCont
        tmux new -d -s PCO_WriterServerCont
        tmux send-keys -t PCO_WriterServerCont "ssh -X control@writernode" ENTER
        tmux send-keys -t PCO_WriterServerCont "cd /home/control/BEATSH5Writer; source /opt/operation/p3.9/bin/activate; ./start_writer --scanMode PCO-MICOS-Cont" ENTER

      elif [ "$process" == "PCO_ContMEDM" ] ; then
        ssh -X control@localhost "
          nohup medm -x -macro "P=tomoscanBEATS:,R=PcoMicosCont:,BEAMLINE=tomoScan_BEATS_PCO_MICOS_Cont" /opt/epics/support/BEATS_tomoscan/tomoScanApp/op/adl/tomoScan.adl &
        "
      #---------------------FLIR Step Scan --------------------#
      elif [ "$process" == "FLIR_StepTomoscanIOC" ] ; then
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_FLIR_MICOS_Step
        tmux new -d -s FLIR_StepTomoscanIOC './start_IOC' 

      elif [ "$process" == "FLIR_PythonServerStep" ] ; then
        tmux kill-session -t FLIR_PythonServerStep
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_FLIR_MICOS_Step
        #source /opt/SW/venv3.9/bin/activate
        tmux new -d -s FLIR_PythonServerStep
        tmux send-keys -t FLIR_PythonServerStep "p3; python -i start_tomoscan.py" ENTER 

      elif [ "$process" == "FLIR_WriterServerStep" ] ; then
        tmux kill-session -t FLIR_WriterServerStep
        tmux new -d -s FLIR_WriterServerStep 
        tmux send-keys -t FLIR_WriterServerStep "ssh -X control@writernode" ENTER
        tmux send-keys -t FLIR_WriterServerStep "cd /home/control/BEATSH5Writer; source /opt/operation/p3.9/bin/activate; ./start_writer --scanMode FLIR-MICOS-Step" ENTER

      elif [ "$process" == "FLIR_StepMEDM" ] ; then
        ssh -X control@localhost "
          nohup medm -x -macro "P=tomoscanBEATS:,R=FlirMicosStep:,BEAMLINE=tomoScan_BEATS_FLIR_MICOS_Step" /opt/epics/support/BEATS_tomoscan/tomoScanApp/op/adl/tomoScan-Step.adl &
        "
      #---------------------FLIR Continuous Scan --------------------#
      elif [ "$process" == "FLIR_ContTomoscanIOC" ] ; then
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_FLIR_MICOS_Cont 
        tmux new -d -s FLIR_ContTomoscanIOC './start_IOC' 

      elif [ "$process" == "FLIR_PythonServerCont" ] ; then
        tmux kill-session -t FLIR_PythonServerCont
        cd /opt/epics/support/BEATS_tomoscan/iocBoot/iocTomoScan_BEATS_FLIR_MICOS_Cont 
        #source /opt/SW/venv3.9/bin/activate
        tmux new -d -s FLIR_PythonServerCont
        tmux send-keys -t FLIR_PythonServerCont "p3; python -i start_tomoscan.py" ENTER 
            
      elif [ "$process" == "FLIR_WriterServerCont" ] ; then
        tmux kill-session -t FLIR_WriterServerCont
        tmux new -d -s FLIR_WriterServerCont
        tmux send-keys -t FLIR_WriterServerCont "ssh -X control@writernode" ENTER
        tmux send-keys -t FLIR_WriterServerCont "cd /home/control/BEATSH5Writer; source /opt/operation/p3.9/bin/activate; ./start_writer --scanMode FLIR-MICOS-Cont" ENTER
                        
      elif [ "$process" == "FLIR_ContMEDM" ] ; then
        ssh -X control@localhost "
          nohup medm -x -macro "P=tomoscanBEATS:,R=FlirMicosCont:,BEAMLINE=tomoScan_BEATS_FLIR_MICOS_Cont" /opt/epics/support/BEATS_tomoscan/tomoScanApp/op/adl/tomoScan.adl &
        "
    #-----------------------------------------#
      elif [ "$process" == "ImageJ" ] ; then
        cd /home/control/ImageJ
        ./ImageJ
      else 
          echo "Unknow process option has been provided!!"
    fi
      shift 2
      ;;
    -h | --help)
      printf "\n"
      echo "============= Start BEATS process options ============="
      echo " >>>>> Commom IOCs <<<<<"
      echo " --process shutterIOC "
      echo " --process MotorIOC"
      echo " --process tomoscanSupportIOC"
      echo " --process writerSupportIOC"
      echo " --------------------------"
      echo " >>>>> PCO & FLIR IOCs <<<<<"
      echo " --process FLIRIOC"
      echo " --process FLIRDriver"
      echo " --process PCODriver"
      echo " --------------------------"
      echo " >>>>> PCO Step or Continuous Scan <<<<<"
      echo -e " Step Scan: \t\t\t\t Continuous Scan:"                                       
      echo -e " --process PCO_StepTomoscanIOC \t\t --process PCO_ContTomoscanIOC"
      echo -e " --process PCO_PythonServerStep \t --process PCO_PythonServerCont"
      echo -e " --process PCO_WriterServerStep \t --process PCO_WriterServerCont"
      echo -e " --process PCO_StepMEDM \t\t --process PCO_ContMEDM"
      echo " --------------------------"
      echo " >>>>> FLIR Step or Continuous Scan <<<<<"
      echo -e " Step Scan: \t\t\t\t Continuous Scan:"                                       
      echo -e " --process FLIR_StepTomoscanIOC \t --process FLIR_ContTomoscanIOC"
      echo -e " --process FLIR_PythonServerStep \t --process FLIR_PythonServerCont"
      echo -e " --process FLIR_WriterServerStep \t --process FLIR_WriterServerCont"
      echo -e " --process FLIR_StepMEDM \t\t --process FLIR_ContMEDM"
      echo " --------------------------"
      echo " >>>>> ImageJ <<<<<"
      echo " --process ImageJ"
      echo "===================================================="
      printf "\n"
      exit 2
      ;;
    --)
      shift;
      break
      ;;
    *)
      echo "Unexpected option: $1"
      ;;
  esac
done

echo $process
